all:
  hosts:
    gateway_server:
      ansible_host: 35.180.243.227
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/Downloads/ansible.pem"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
