all:
  hosts:
    gateway_server:
      ansible_host: 72.60.90.182
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/midpoint"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
